const { test, expect } = require('@playwright/test');

test('API chaining - create and get record', async ({ request }) => {

  const apiKey = process.env.REQRES_API_KEY;
  const projectId = process.env.REQRES_PROJECT_ID;

  // Step 1: Create a product record
  const createResponse = await request.post(
    `/api/collections/products/records?project_id=${projectId}`,
    {
      headers: {
        'x-api-key': apiKey,
        'X-Reqres-Env': 'prod'
      },
      data: {
        data: {
          name: 'Playwright Product',
          price: 99.99
        }
      }
    }
  );

  // Check that the record was created
  expect(createResponse.status()).toBe(201);

  // Read the create response
  const createBody = await createResponse.json();

  // Store the generated ID
  const recordId = createBody.id;

  // Check that an ID was created
  expect(recordId).toBeTruthy();

  // Step 2: Get the same record using the ID from Step 1
  const getResponse = await request.get(
    `/api/collections/products/records/${recordId}?project_id=${projectId}`,
    {
      headers: {
        'x-api-key': apiKey,
        'X-Reqres-Env': 'prod'
      }
    }
  );

  // Check that the GET request was successful
  expect(getResponse.status()).toBe(200);

  // Read the GET response
  const getBody = await getResponse.json();

  // Validate that the returned ID is the same
  expect(getBody.id).toBe(recordId);
});

/*
CONCEPT: api-chaining.spec.js

WHAT ARE WE DOING:
We are using data from one API response in the next API request.

REQUEST:
1. POST /api/collections/products/records?project_id=PROJECT_ID
2. GET /api/collections/products/records/{recordId}?project_id=PROJECT_ID

EXPECTED RESPONSE:
POST -> 201 Created
GET -> 200 OK

VALIDATION:
We create a record, get its generated ID, use that ID in the next request,
and verify that the same record is returned.

SAMPLE OUTPUT:

Step 1 - POST Create:
Response Status: 201

Generated Record ID:
<generated-id>

Step 2 - GET Same Record:
Response Status: 200

Validated Record ID:
<generated-id>

Playwright Result:
1 passed

LINE-BY-LINE EXPLANATION:

1. const apiKey = process.env.REQRES_API_KEY;
   -> I read the API key from an environment variable.

2. const projectId = process.env.REQRES_PROJECT_ID;
   -> I read the ReqRes project ID from an environment variable.

3. request.post(...)
   -> I send the first request to create a product.

4. data: { data: { ... } }
   -> I send the product data in the request body.

5. expect(createResponse.status()).toBe(201);
   -> I verify that the record was created.

6. const createBody = await createResponse.json();
   -> I read the create response.

7. const recordId = createBody.id;
   -> I take the generated record ID from the response.

8. request.get(`.../${recordId}...`)
   -> I use the ID from the first response in the second request.

9. expect(getResponse.status()).toBe(200);
   -> I verify that the record can be retrieved.

10. expect(getBody.id).toBe(recordId);
    -> I verify that the ID returned by the GET matches the created ID.

INTERVIEW FOLLOW-UP QUESTIONS:

Q1. What is API chaining?
-> Using data from one API response in a later API request.

Q2. Why do we store recordId?
-> Because we need the ID generated by the create request for the next request.

Q3. Where is the actual chaining happening?
-> The value from createBody.id is used inside the GET URL.
*/